// Comprehensive exercise library - 150+ exercises organized by muscle group
// Each exercise has: name, slug, muscleGroup, equipment, category, difficulty, instructions, secondaryMuscles

interface ExerciseEntry {
  name: string;
  slug: string;
  muscleGroup: string;
  equipment: string;
  category: string;
  difficulty: string;
  instructions: string[];
  secondaryMuscles?: string[];
}

export const exerciseLibrary: ExerciseEntry[] = [
  // ==================== CHEST (Peito) ====================
  { name: 'Bench Press', slug: 'bench-press', muscleGroup: 'CHEST', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Deite no banco plano', 'Segure a barra na largura dos ombros', 'Desça a barra até o peito', 'Empurre de volta até a extensão completa'], secondaryMuscles: ['TRICEPS', 'SHOULDERS'] },
  { name: 'Incline Bench Press', slug: 'incline-bench-press', muscleGroup: 'CHEST', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Ajuste o banco em 30-45 graus', 'Segure a barra na largura dos ombros', 'Desça até o peito superior', 'Empurre de volta'], secondaryMuscles: ['TRICEPS', 'SHOULDERS'] },
  { name: 'Decline Bench Press', slug: 'decline-bench-press', muscleGroup: 'CHEST', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Deite no banco declinado', 'Prenda os pés nos apoios', 'Desça a barra até o peito inferior', 'Empurre de volta'], secondaryMuscles: ['TRICEPS'] },
  { name: 'Dumbbell Bench Press', slug: 'dumbbell-bench-press', muscleGroup: 'CHEST', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Deite no banco com halteres', 'Posicione os halteres ao lado do peito', 'Empurre para cima e junte no topo', 'Desça controladamente'], secondaryMuscles: ['TRICEPS', 'SHOULDERS'] },
  { name: 'Incline Dumbbell Press', slug: 'incline-dumbbell-press', muscleGroup: 'CHEST', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Banco inclinado 30-45 graus', 'Halteres ao lado do peito', 'Empurre para cima', 'Desça devagar'], secondaryMuscles: ['TRICEPS', 'SHOULDERS'] },
  { name: 'Dumbbell Fly', slug: 'dumbbell-fly', muscleGroup: 'CHEST', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Deite no banco plano com halteres', 'Braços estendidos acima do peito', 'Abra os braços em arco', 'Feche os braços como um abraço'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Incline Dumbbell Fly', slug: 'incline-dumbbell-fly', muscleGroup: 'CHEST', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Banco inclinado 30-45 graus', 'Abra os braços em arco controlado', 'Junte no topo contraindo o peito'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Cable Crossover', slug: 'cable-crossover', muscleGroup: 'CHEST', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Posicione as polias na posição alta', 'Um passo à frente', 'Traga as mãos juntas na frente', 'Contraia o peito no final'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Low Cable Fly', slug: 'low-cable-fly', muscleGroup: 'CHEST', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polias na posição baixa', 'Traga as mãos para cima e juntas', 'Foco no peito superior'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Machine Chest Press', slug: 'machine-chest-press', muscleGroup: 'CHEST', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Ajuste o assento', 'Empurre as alças para frente', 'Estenda os braços completamente', 'Retorne devagar'], secondaryMuscles: ['TRICEPS'] },
  { name: 'Pec Deck', slug: 'pec-deck', muscleGroup: 'CHEST', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente na máquina', 'Posicione os braços nas almofadas', 'Junte os braços na frente', 'Contraia o peito'] },
  { name: 'Push Up', slug: 'push-up', muscleGroup: 'CHEST', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Posição de prancha', 'Mãos na largura dos ombros', 'Desça o corpo até quase tocar o chão', 'Empurre de volta'], secondaryMuscles: ['TRICEPS', 'CORE'] },
  { name: 'Dips (Chest)', slug: 'dips-chest', muscleGroup: 'CHEST', equipment: 'DIP_BAR', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Incline o tronco à frente', 'Desça até 90 graus nos cotovelos', 'Empurre para cima', 'Foco na contração do peito'], secondaryMuscles: ['TRICEPS', 'SHOULDERS'] },
  { name: 'Smith Machine Bench Press', slug: 'smith-bench-press', muscleGroup: 'CHEST', equipment: 'SMITH_MACHINE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Deite no banco sob o Smith', 'Desça a barra controladamente', 'Empurre para cima'], secondaryMuscles: ['TRICEPS'] },

  // ==================== BACK (Costas) ====================
  { name: 'Deadlift', slug: 'deadlift', muscleGroup: 'BACK', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'ADVANCED', instructions: ['Posicione os pés na largura dos ombros', 'Agache e segure a barra', 'Mantenha as costas retas', 'Levante com as pernas e quadril', 'Finalize em pé com ombros para trás'], secondaryMuscles: ['HAMSTRINGS', 'GLUTES', 'CORE'] },
  { name: 'Barbell Row', slug: 'barbell-row', muscleGroup: 'BACK', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Incline o tronco a 45 graus', 'Segure a barra com pegada pronada', 'Puxe a barra até o abdômen', 'Desça controladamente'], secondaryMuscles: ['BICEPS'] },
  { name: 'Pendlay Row', slug: 'pendlay-row', muscleGroup: 'BACK', equipment: 'BARBELL', category: 'POWER', difficulty: 'ADVANCED', instructions: ['Tronco paralelo ao chão', 'Barra no chão a cada rep', 'Puxe explosivamente até o abdômen', 'Retorne ao chão'], secondaryMuscles: ['BICEPS', 'CORE'] },
  { name: 'Lat Pulldown', slug: 'lat-pulldown', muscleGroup: 'BACK', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente na máquina, joelhos presos', 'Pegada ampla na barra', 'Puxe até o peito superior', 'Retorne devagar'], secondaryMuscles: ['BICEPS'] },
  { name: 'Close Grip Lat Pulldown', slug: 'close-grip-lat-pulldown', muscleGroup: 'BACK', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Use o triângulo ou barra V', 'Puxe até o peito', 'Cotovelos para trás', 'Contraia as costas'], secondaryMuscles: ['BICEPS'] },
  { name: 'Pull Up', slug: 'pull-up', muscleGroup: 'BACK', equipment: 'PULL_UP_BAR', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pegada pronada na largura dos ombros', 'Puxe o queixo acima da barra', 'Desça controladamente', 'Extensão completa dos braços'], secondaryMuscles: ['BICEPS', 'CORE'] },
  { name: 'Chin Up', slug: 'chin-up', muscleGroup: 'BACK', equipment: 'PULL_UP_BAR', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pegada supinada', 'Puxe o queixo acima da barra', 'Foco nos bíceps e costas'], secondaryMuscles: ['BICEPS'] },
  { name: 'Dumbbell Row', slug: 'dumbbell-row', muscleGroup: 'BACK', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Apoie um joelho no banco', 'Puxe o halter até a cintura', 'Cotovelo para trás', 'Desça controladamente'], secondaryMuscles: ['BICEPS'] },
  { name: 'Seated Cable Row', slug: 'seated-cable-row', muscleGroup: 'BACK', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente com pés nos apoios', 'Puxe o cabo até o abdômen', 'Aperte as escápulas', 'Retorne devagar'], secondaryMuscles: ['BICEPS'] },
  { name: 'T-Bar Row', slug: 't-bar-row', muscleGroup: 'BACK', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Posicione a barra no landmine', 'Incline e puxe com ambas as mãos', 'Contraia as costas no topo'], secondaryMuscles: ['BICEPS'] },
  { name: 'Face Pull', slug: 'face-pull', muscleGroup: 'BACK', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia na posição alta', 'Puxe a corda em direção ao rosto', 'Abra os braços e aperte as escápulas', 'Retorne controladamente'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Inverted Row', slug: 'inverted-row', muscleGroup: 'BACK', equipment: 'BODYWEIGHT', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Deite sob a barra', 'Puxe o peito até a barra', 'Corpo reto como prancha', 'Desça devagar'], secondaryMuscles: ['BICEPS', 'CORE'] },
  { name: 'Machine Row', slug: 'machine-row', muscleGroup: 'BACK', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Ajuste o assento e o peito', 'Puxe as alças', 'Contraia as costas', 'Retorne devagar'], secondaryMuscles: ['BICEPS'] },
  { name: 'Straight Arm Pulldown', slug: 'straight-arm-pulldown', muscleGroup: 'BACK', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia alta, braços estendidos', 'Puxe a barra até as coxas', 'Mantenha os braços retos', 'Contraia o latíssimo'] },

  // ==================== SHOULDERS (Ombros) ====================
  { name: 'Overhead Press', slug: 'overhead-press', muscleGroup: 'SHOULDERS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Em pé, barra na altura do peito', 'Empurre a barra acima da cabeça', 'Extensão completa dos braços', 'Desça até o peito'], secondaryMuscles: ['TRICEPS', 'CORE'] },
  { name: 'Seated Dumbbell Press', slug: 'seated-dumbbell-press', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Sente com apoio nas costas', 'Halteres na altura dos ombros', 'Empurre para cima', 'Desça até 90 graus'], secondaryMuscles: ['TRICEPS'] },
  { name: 'Arnold Press', slug: 'arnold-press', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Inicie com halteres na frente, palmas viradas', 'Gire as palmas enquanto empurra para cima', 'Extensão completa no topo', 'Retorne girando de volta'], secondaryMuscles: ['TRICEPS'] },
  { name: 'Lateral Raise', slug: 'lateral-raise', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Em pé, halteres ao lado', 'Levante os braços lateralmente', 'Até a altura dos ombros', 'Desça devagar'] },
  { name: 'Cable Lateral Raise', slug: 'cable-lateral-raise', muscleGroup: 'SHOULDERS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa, cabo cruzado', 'Levante o braço lateralmente', 'Controle a descida'] },
  { name: 'Front Raise', slug: 'front-raise', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Em pé, halteres à frente das coxas', 'Levante os braços à frente', 'Até a altura dos ombros', 'Desça devagar'] },
  { name: 'Reverse Fly', slug: 'reverse-fly', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Incline o tronco à frente', 'Levante os braços lateralmente', 'Aperte as escápulas', 'Desça devagar'], secondaryMuscles: ['BACK'] },
  { name: 'Upright Row', slug: 'upright-row', muscleGroup: 'SHOULDERS', equipment: 'BARBELL', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Segure a barra com pegada estreita', 'Puxe até o queixo', 'Cotovelos acima dos ombros', 'Desça devagar'], secondaryMuscles: ['BICEPS'] },
  { name: 'Machine Shoulder Press', slug: 'machine-shoulder-press', muscleGroup: 'SHOULDERS', equipment: 'MACHINE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Ajuste o assento', 'Empurre as alças para cima', 'Extensão completa', 'Retorne devagar'], secondaryMuscles: ['TRICEPS'] },
  { name: 'Barbell Shrug', slug: 'barbell-shrug', muscleGroup: 'SHOULDERS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Segure a barra na frente', 'Encolha os ombros para cima', 'Segure no topo', 'Desça devagar'] },
  { name: 'Dumbbell Shrug', slug: 'dumbbell-shrug', muscleGroup: 'SHOULDERS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Halteres ao lado do corpo', 'Encolha os ombros', 'Segure 1-2 segundos no topo'] },

  // ==================== BICEPS (Bíceps) ====================
  { name: 'Barbell Curl', slug: 'barbell-curl', muscleGroup: 'BICEPS', equipment: 'BARBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Em pé, barra com pegada supinada', 'Flexione os braços', 'Contraia os bíceps no topo', 'Desça devagar'] },
  { name: 'EZ Bar Curl', slug: 'ez-bar-curl', muscleGroup: 'BICEPS', equipment: 'EZ_BAR', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Pegada na curva da barra EZ', 'Flexione mantendo cotovelos fixos', 'Contraia no topo'] },
  { name: 'Dumbbell Curl', slug: 'dumbbell-curl', muscleGroup: 'BICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Halteres ao lado do corpo', 'Flexione alternadamente ou juntos', 'Supine o punho durante o movimento'] },
  { name: 'Hammer Curl', slug: 'hammer-curl', muscleGroup: 'BICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Pegada neutra (palmas viradas)', 'Flexione mantendo pegada', 'Trabalha braquial e braquiorradial'], secondaryMuscles: ['FOREARMS'] },
  { name: 'Incline Dumbbell Curl', slug: 'incline-dumbbell-curl', muscleGroup: 'BICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Banco inclinado 45 graus', 'Braços pendurados', 'Flexione mantendo cotovelos fixos', 'Maior amplitude do bíceps'] },
  { name: 'Preacher Curl', slug: 'preacher-curl', muscleGroup: 'BICEPS', equipment: 'EZ_BAR', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Apoie os braços no banco Scott', 'Flexione a barra', 'Contraia no topo', 'Desça controladamente'] },
  { name: 'Cable Curl', slug: 'cable-curl', muscleGroup: 'BICEPS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa com barra reta', 'Flexione mantendo cotovelos fixos', 'Tensão constante no bíceps'] },
  { name: 'Concentration Curl', slug: 'concentration-curl', muscleGroup: 'BICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente, cotovelo apoiado na coxa', 'Flexione o halter', 'Contraia o bíceps no topo', 'Desça devagar'] },
  { name: 'Spider Curl', slug: 'spider-curl', muscleGroup: 'BICEPS', equipment: 'EZ_BAR', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Deite de bruços no banco inclinado', 'Braços pendurados com barra', 'Flexione até contrair', 'Foco na contração peak'] },
  { name: 'Cable Hammer Curl', slug: 'cable-hammer-curl', muscleGroup: 'BICEPS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa com corda', 'Pegada neutra', 'Flexione mantendo cotovelos fixos'], secondaryMuscles: ['FOREARMS'] },

  // ==================== TRICEPS (Tríceps) ====================
  { name: 'Tricep Pushdown', slug: 'tricep-pushdown', muscleGroup: 'TRICEPS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia alta com barra reta', 'Empurre para baixo', 'Extensão completa dos braços', 'Retorne devagar'] },
  { name: 'Rope Pushdown', slug: 'rope-pushdown', muscleGroup: 'TRICEPS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia alta com corda', 'Empurre para baixo e abra as pontas', 'Contraia os tríceps', 'Retorne controladamente'] },
  { name: 'Skull Crusher', slug: 'skull-crusher', muscleGroup: 'TRICEPS', equipment: 'EZ_BAR', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Deite no banco, braços estendidos', 'Flexione apenas os cotovelos', 'Desça a barra até a testa', 'Estenda de volta'] },
  { name: 'Close Grip Bench Press', slug: 'close-grip-bench-press', muscleGroup: 'TRICEPS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pegada estreita na barra', 'Desça até o peito', 'Empurre focando nos tríceps', 'Cotovelos próximos ao corpo'], secondaryMuscles: ['CHEST'] },
  { name: 'Overhead Tricep Extension', slug: 'overhead-tricep-extension', muscleGroup: 'TRICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Halter atrás da cabeça com ambas as mãos', 'Estenda os braços acima', 'Mantenha cotovelos próximos', 'Desça devagar'] },
  { name: 'Cable Overhead Extension', slug: 'cable-overhead-extension', muscleGroup: 'TRICEPS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa, de costas', 'Corda atrás da cabeça', 'Estenda os braços para frente e acima'] },
  { name: 'Tricep Kickback', slug: 'tricep-kickback', muscleGroup: 'TRICEPS', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Incline o tronco à frente', 'Cotovelo a 90 graus', 'Estenda o braço para trás', 'Contraia o tríceps no topo'] },
  { name: 'Dips (Tricep)', slug: 'dips-tricep', muscleGroup: 'TRICEPS', equipment: 'DIP_BAR', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Corpo ereto (não incline)', 'Desça até 90 graus nos cotovelos', 'Empurre para cima', 'Foco nos tríceps'], secondaryMuscles: ['CHEST'] },
  { name: 'Diamond Push Up', slug: 'diamond-push-up', muscleGroup: 'TRICEPS', equipment: 'BODYWEIGHT', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Mãos juntas formando diamante', 'Desça o peito até as mãos', 'Empurre de volta', 'Foco nos tríceps'], secondaryMuscles: ['CHEST'] },

  // ==================== QUADS (Quadríceps) ====================
  { name: 'Squat', slug: 'squat', muscleGroup: 'QUADS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Barra nas costas, pés na largura dos ombros', 'Agache até as coxas ficarem paralelas', 'Joelhos alinhados com os pés', 'Empurre o chão para subir'], secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'CORE'] },
  { name: 'Front Squat', slug: 'front-squat', muscleGroup: 'QUADS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'ADVANCED', instructions: ['Barra na frente dos ombros', 'Cotovelos altos', 'Agache mantendo tronco ereto', 'Maior ênfase nos quadríceps'], secondaryMuscles: ['GLUTES', 'CORE'] },
  { name: 'Goblet Squat', slug: 'goblet-squat', muscleGroup: 'QUADS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Segure o halter/kettlebell no peito', 'Agache profundamente', 'Mantenha tronco ereto', 'Ótimo para iniciantes'], secondaryMuscles: ['GLUTES', 'CORE'] },
  { name: 'Leg Press', slug: 'leg-press', muscleGroup: 'QUADS', equipment: 'MACHINE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Pés na plataforma, largura dos ombros', 'Desça até 90 graus nos joelhos', 'Empurre sem travar os joelhos', 'Costas sempre coladas no encosto'], secondaryMuscles: ['GLUTES'] },
  { name: 'Hack Squat', slug: 'hack-squat', muscleGroup: 'QUADS', equipment: 'MACHINE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Costas no apoio da máquina', 'Pés na plataforma', 'Agache até 90 graus', 'Empurre para cima'], secondaryMuscles: ['GLUTES'] },
  { name: 'Lunges', slug: 'lunges', muscleGroup: 'QUADS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Dê um passo à frente', 'Desça até o joelho de trás quase tocar o chão', 'Empurre de volta à posição inicial', 'Alterne as pernas'], secondaryMuscles: ['GLUTES', 'HAMSTRINGS'] },
  { name: 'Walking Lunges', slug: 'walking-lunges', muscleGroup: 'QUADS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Halteres ao lado do corpo', 'Dê um passo à frente e agache', 'Empurre para o próximo passo', 'Continue caminhando'], secondaryMuscles: ['GLUTES', 'HAMSTRINGS'] },
  { name: 'Bulgarian Split Squat', slug: 'bulgarian-split-squat', muscleGroup: 'QUADS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pé traseiro no banco', 'Agache com a perna da frente', 'Joelho alinhado com o pé', 'Empurre para cima'], secondaryMuscles: ['GLUTES'] },
  { name: 'Leg Extension', slug: 'leg-extension', muscleGroup: 'QUADS', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente na máquina', 'Apoio nas canelas', 'Estenda as pernas completamente', 'Contraia os quadríceps no topo'] },
  { name: 'Smith Machine Squat', slug: 'smith-machine-squat', muscleGroup: 'QUADS', equipment: 'SMITH_MACHINE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Barra nos ombros no Smith', 'Pés ligeiramente à frente', 'Agache controladamente', 'Empurre para cima'], secondaryMuscles: ['GLUTES'] },
  { name: 'Sissy Squat', slug: 'sissy-squat', muscleGroup: 'QUADS', equipment: 'BODYWEIGHT', category: 'HYPERTROPHY', difficulty: 'ADVANCED', instructions: ['Em pé, segure em algo para equilíbrio', 'Incline o corpo para trás', 'Flexione os joelhos mantendo quadril estendido', 'Suba controladamente'] },
  { name: 'Step Up', slug: 'step-up', muscleGroup: 'QUADS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Banco ou caixa na altura do joelho', 'Suba com uma perna', 'Estenda completamente', 'Desça controladamente'], secondaryMuscles: ['GLUTES'] },

  // ==================== HAMSTRINGS (Posteriores) ====================
  { name: 'Romanian Deadlift', slug: 'romanian-deadlift', muscleGroup: 'HAMSTRINGS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Barra na frente das coxas', 'Joelhos levemente flexionados', 'Incline empurrando o quadril para trás', 'Desça até sentir alongamento', 'Retorne contraindo glúteos'], secondaryMuscles: ['GLUTES', 'BACK'] },
  { name: 'Dumbbell Romanian Deadlift', slug: 'dumbbell-rdl', muscleGroup: 'HAMSTRINGS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Halteres na frente das coxas', 'Incline empurrando quadril para trás', 'Desça até sentir alongamento', 'Retorne apertando glúteos'], secondaryMuscles: ['GLUTES'] },
  { name: 'Leg Curl', slug: 'leg-curl', muscleGroup: 'HAMSTRINGS', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Deite de bruços na máquina', 'Apoio nos tornozelos', 'Flexione as pernas', 'Contraia os posteriores'] },
  { name: 'Seated Leg Curl', slug: 'seated-leg-curl', muscleGroup: 'HAMSTRINGS', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente na máquina', 'Apoio nas canelas', 'Flexione as pernas para baixo', 'Contraia os posteriores'] },
  { name: 'Stiff Leg Deadlift', slug: 'stiff-leg-deadlift', muscleGroup: 'HAMSTRINGS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pernas quase retas', 'Desça a barra ao longo das pernas', 'Alongue os posteriores', 'Suba contraindo glúteos'], secondaryMuscles: ['GLUTES', 'BACK'] },
  { name: 'Good Morning', slug: 'good-morning', muscleGroup: 'HAMSTRINGS', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Barra nas costas como no squat', 'Incline o tronco à frente', 'Quadril para trás', 'Retorne à posição ereta'], secondaryMuscles: ['GLUTES', 'BACK'] },
  { name: 'Nordic Hamstring Curl', slug: 'nordic-curl', muscleGroup: 'HAMSTRINGS', equipment: 'BODYWEIGHT', category: 'STRENGTH', difficulty: 'ADVANCED', instructions: ['Ajoelhado, pés presos', 'Incline o corpo à frente lentamente', 'Use os posteriores para freiar', 'Empurre do chão se necessário'] },
  { name: 'Single Leg Deadlift', slug: 'single-leg-deadlift', muscleGroup: 'HAMSTRINGS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Em pé numa perna', 'Incline à frente estendendo a outra perna', 'Halter na mão oposta', 'Retorne ao equilíbrio'], secondaryMuscles: ['GLUTES', 'CORE'] },

  // ==================== GLUTES (Glúteos) ====================
  { name: 'Hip Thrust', slug: 'hip-thrust', muscleGroup: 'GLUTES', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Costas apoiadas no banco', 'Barra sobre o quadril', 'Empurre o quadril para cima', 'Contraia os glúteos no topo', 'Desça controladamente'], secondaryMuscles: ['HAMSTRINGS'] },
  { name: 'Glute Bridge', slug: 'glute-bridge', muscleGroup: 'GLUTES', equipment: 'BODYWEIGHT', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Deite de costas, joelhos flexionados', 'Empurre o quadril para cima', 'Contraia os glúteos', 'Desça devagar'], secondaryMuscles: ['HAMSTRINGS'] },
  { name: 'Cable Kickback', slug: 'cable-kickback', muscleGroup: 'GLUTES', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa, caneleira no tornozelo', 'Chute a perna para trás', 'Contraia o glúteo no topo', 'Retorne controladamente'] },
  { name: 'Sumo Deadlift', slug: 'sumo-deadlift', muscleGroup: 'GLUTES', equipment: 'BARBELL', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pés bem abertos, pontas para fora', 'Segure a barra entre as pernas', 'Levante estendendo quadril e pernas', 'Aperte os glúteos no topo'], secondaryMuscles: ['QUADS', 'HAMSTRINGS', 'BACK'] },
  { name: 'Cable Pull Through', slug: 'cable-pull-through', muscleGroup: 'GLUTES', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Polia baixa, de costas', 'Puxe o cabo entre as pernas', 'Estenda o quadril', 'Contraia os glúteos'], secondaryMuscles: ['HAMSTRINGS'] },

  // ==================== CALVES (Panturrilhas) ====================
  { name: 'Calf Raise', slug: 'calf-raise', muscleGroup: 'CALVES', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Em pé na máquina', 'Suba nas pontas dos pés', 'Segure no topo 1-2 segundos', 'Desça abaixo do nível'] },
  { name: 'Seated Calf Raise', slug: 'seated-calf-raise', muscleGroup: 'CALVES', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Sente na máquina', 'Apoio sobre os joelhos', 'Suba nas pontas dos pés', 'Foco no sóleo'] },
  { name: 'Standing Calf Raise', slug: 'standing-calf-raise', muscleGroup: 'CALVES', equipment: 'DUMBBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Em pé em um step com halteres', 'Suba nas pontas dos pés', 'Desça além do nível do step', 'Amplitude completa'] },
  { name: 'Donkey Calf Raise', slug: 'donkey-calf-raise', muscleGroup: 'CALVES', equipment: 'MACHINE', category: 'HYPERTROPHY', difficulty: 'INTERMEDIATE', instructions: ['Incline o tronco à frente', 'Apoio nas costas', 'Suba nas pontas dos pés', 'Grande amplitude'] },

  // ==================== CORE (Core/Abs) ====================
  { name: 'Plank', slug: 'plank', muscleGroup: 'CORE', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Posição de prancha nos antebraços', 'Corpo reto da cabeça aos pés', 'Contraia o abdômen', 'Mantenha por tempo'] },
  { name: 'Cable Crunch', slug: 'cable-crunch', muscleGroup: 'ABS', equipment: 'CABLE', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Ajoelhado na polia alta', 'Segure a corda atrás da cabeça', 'Flexione o tronco para baixo', 'Contraia o abdômen'] },
  { name: 'Hanging Leg Raise', slug: 'hanging-leg-raise', muscleGroup: 'ABS', equipment: 'PULL_UP_BAR', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Pendurado na barra', 'Levante as pernas estendidas', 'Até a horizontal ou além', 'Desça controladamente'], secondaryMuscles: ['CORE'] },
  { name: 'Ab Wheel Rollout', slug: 'ab-wheel-rollout', muscleGroup: 'ABS', equipment: 'OTHER', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Ajoelhado com a roda', 'Role para frente estendendo o corpo', 'Mantenha o core contraído', 'Retorne à posição inicial'], secondaryMuscles: ['CORE'] },
  { name: 'Russian Twist', slug: 'russian-twist', muscleGroup: 'ABS', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Sente com pés elevados', 'Tronco inclinado para trás', 'Gire o tronco lado a lado', 'Com ou sem peso'], secondaryMuscles: ['CORE'] },
  { name: 'Bicycle Crunch', slug: 'bicycle-crunch', muscleGroup: 'ABS', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Deite de costas, mãos na cabeça', 'Pedale as pernas no ar', 'Cotovelo toca o joelho oposto', 'Alterne os lados'] },
  { name: 'Side Plank', slug: 'side-plank', muscleGroup: 'CORE', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Deite de lado, apoio no antebraço', 'Eleve o quadril', 'Corpo reto', 'Mantenha por tempo'] },
  { name: 'Dead Bug', slug: 'dead-bug', muscleGroup: 'CORE', equipment: 'BODYWEIGHT', category: 'ENDURANCE', difficulty: 'BEGINNER', instructions: ['Deite de costas, braços e pernas elevados', 'Estenda braço e perna opostos', 'Mantenha costas no chão', 'Alterne os lados'] },
  { name: 'Mountain Climber', slug: 'mountain-climber', muscleGroup: 'CORE', equipment: 'BODYWEIGHT', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Posição de prancha alta', 'Traga um joelho ao peito', 'Alterne rapidamente', 'Mantenha o core contraído'] },
  { name: 'Decline Sit Up', slug: 'decline-sit-up', muscleGroup: 'ABS', equipment: 'BODYWEIGHT', category: 'STRENGTH', difficulty: 'INTERMEDIATE', instructions: ['Banco declinado, pés presos', 'Cruze os braços no peito', 'Suba contraindo o abdômen', 'Desça devagar'] },
  { name: 'Woodchop', slug: 'woodchop', muscleGroup: 'CORE', equipment: 'CABLE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Polia alta ou baixa', 'Gire o tronco puxando o cabo', 'Movimento diagonal', 'Controle a volta'], secondaryMuscles: ['SHOULDERS'] },
  { name: 'Pallof Press', slug: 'pallof-press', muscleGroup: 'CORE', equipment: 'CABLE', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Polia na altura do peito, de lado', 'Estenda os braços à frente', 'Resista à rotação', 'Retorne ao peito'] },

  // ==================== FOREARMS (Antebraços) ====================
  { name: 'Wrist Curl', slug: 'wrist-curl', muscleGroup: 'FOREARMS', equipment: 'BARBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Antebraços apoiados, palmas para cima', 'Flexione os punhos para cima', 'Contraia no topo', 'Desça devagar'] },
  { name: 'Reverse Wrist Curl', slug: 'reverse-wrist-curl', muscleGroup: 'FOREARMS', equipment: 'BARBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Antebraços apoiados, palmas para baixo', 'Estenda os punhos para cima', 'Contraia no topo'] },
  { name: 'Reverse Curl', slug: 'reverse-curl', muscleGroup: 'FOREARMS', equipment: 'BARBELL', category: 'HYPERTROPHY', difficulty: 'BEGINNER', instructions: ['Pegada pronada na barra', 'Flexione os braços', 'Trabalha braquiorradial'], secondaryMuscles: ['BICEPS'] },
  { name: 'Farmer Walk', slug: 'farmer-walk', muscleGroup: 'FOREARMS', equipment: 'DUMBBELL', category: 'STRENGTH', difficulty: 'BEGINNER', instructions: ['Halteres pesados ao lado', 'Caminhe mantendo postura ereta', 'Agarre firme pelo máximo de tempo'], secondaryMuscles: ['CORE'] },

  // ==================== FULL BODY (Corpo Inteiro) ====================
  { name: 'Clean and Press', slug: 'clean-and-press', muscleGroup: 'FULL_BODY', equipment: 'BARBELL', category: 'POWER', difficulty: 'ADVANCED', instructions: ['Barra no chão, pegada pronada', 'Puxe explosivamente até os ombros', 'Empurre acima da cabeça', 'Retorne ao chão'], secondaryMuscles: ['SHOULDERS', 'BACK', 'QUADS'] },
  { name: 'Thruster', slug: 'thruster', muscleGroup: 'FULL_BODY', equipment: 'BARBELL', category: 'POWER', difficulty: 'INTERMEDIATE', instructions: ['Barra na posição de front squat', 'Agache completamente', 'Suba e empurre a barra acima', 'Um movimento fluido'], secondaryMuscles: ['QUADS', 'SHOULDERS'] },
  { name: 'Burpee', slug: 'burpee', muscleGroup: 'FULL_BODY', equipment: 'BODYWEIGHT', category: 'CARDIO', difficulty: 'INTERMEDIATE', instructions: ['Em pé, agache e coloque as mãos no chão', 'Salte os pés para trás (prancha)', 'Faça uma flexão', 'Salte os pés de volta e pule'], secondaryMuscles: ['CHEST', 'CORE'] },
  { name: 'Kettlebell Swing', slug: 'kettlebell-swing', muscleGroup: 'FULL_BODY', equipment: 'KETTLEBELL', category: 'POWER', difficulty: 'INTERMEDIATE', instructions: ['Pés na largura dos ombros', 'Balance o kettlebell entre as pernas', 'Empurre o quadril para balançar à frente', 'Braços retos, força vem do quadril'], secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'CORE'] },
  { name: 'Turkish Get Up', slug: 'turkish-get-up', muscleGroup: 'FULL_BODY', equipment: 'KETTLEBELL', category: 'STRENGTH', difficulty: 'ADVANCED', instructions: ['Deite com kettlebell em uma mão', 'Levante-se mantendo o peso acima', 'Passe por todas as posições', 'Retorne ao chão'], secondaryMuscles: ['SHOULDERS', 'CORE'] },
  { name: 'Power Clean', slug: 'power-clean', muscleGroup: 'FULL_BODY', equipment: 'BARBELL', category: 'POWER', difficulty: 'ADVANCED', instructions: ['Barra no chão', 'Primeiro puxe até os joelhos', 'Segundo puxe explosivo', 'Receba nos ombros em posição semi-agachada'], secondaryMuscles: ['BACK', 'QUADS', 'SHOULDERS'] },
  { name: 'Man Maker', slug: 'man-maker', muscleGroup: 'FULL_BODY', equipment: 'DUMBBELL', category: 'CARDIO', difficulty: 'ADVANCED', instructions: ['Flexão com halteres', 'Remada de cada lado', 'Agache e levante', 'Press acima da cabeça'], secondaryMuscles: ['CHEST', 'BACK', 'SHOULDERS'] },
  { name: 'Battle Ropes', slug: 'battle-ropes', muscleGroup: 'FULL_BODY', equipment: 'OTHER', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Segure uma ponta em cada mão', 'Balance as cordas alternadamente', 'Mantenha postura atletica', 'Varie os padrões'], secondaryMuscles: ['SHOULDERS', 'CORE'] },

  // ==================== CARDIO (Cardio) ====================
  { name: 'Running (Treadmill)', slug: 'running-treadmill', muscleGroup: 'CARDIO', equipment: 'MACHINE', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Ajuste velocidade e inclinação', 'Mantenha postura ereta', 'Braços balançando naturalmente', 'Ritmo constante ou intervalado'] },
  { name: 'Cycling (Bike)', slug: 'cycling-bike', muscleGroup: 'CARDIO', equipment: 'MACHINE', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Ajuste o assento na altura correta', 'Pedale mantendo ritmo', 'Varie a resistência', 'Postura ereta'] },
  { name: 'Rowing Machine', slug: 'rowing-machine', muscleGroup: 'CARDIO', equipment: 'MACHINE', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Pés nos apoios, segure a alça', 'Empurre com as pernas primeiro', 'Puxe com as costas e braços', 'Retorne na ordem inversa'], secondaryMuscles: ['BACK'] },
  { name: 'Jump Rope', slug: 'jump-rope', muscleGroup: 'CARDIO', equipment: 'OTHER', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Segure as pontas da corda', 'Salte passando a corda por baixo', 'Mantenha cotovelos próximos', 'Saltos leves e rápidos'], secondaryMuscles: ['CALVES'] },
  { name: 'Stair Climber', slug: 'stair-climber', muscleGroup: 'CARDIO', equipment: 'MACHINE', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Suba os degraus continuamente', 'Mantenha postura ereta', 'Não se apoie nos corrimãos', 'Ajuste a velocidade'], secondaryMuscles: ['QUADS', 'GLUTES'] },
  { name: 'Elliptical', slug: 'elliptical', muscleGroup: 'CARDIO', equipment: 'MACHINE', category: 'CARDIO', difficulty: 'BEGINNER', instructions: ['Pés nas plataformas', 'Movimento elíptico natural', 'Use os braços para mais intensidade', 'Ajuste resistência e inclinação'] },
  { name: 'Box Jump', slug: 'box-jump', muscleGroup: 'CARDIO', equipment: 'OTHER', category: 'POWER', difficulty: 'INTERMEDIATE', instructions: ['Em frente à caixa', 'Agache e salte explosivamente', 'Aterrisse suavemente na caixa', 'Desça e repita'], secondaryMuscles: ['QUADS', 'GLUTES'] },
  { name: 'Sled Push', slug: 'sled-push', muscleGroup: 'CARDIO', equipment: 'OTHER', category: 'CARDIO', difficulty: 'INTERMEDIATE', instructions: ['Mãos nas alças do sled', 'Incline o corpo à frente', 'Empurre com as pernas', 'Passos curtos e rápidos'], secondaryMuscles: ['QUADS', 'GLUTES', 'CORE'] },
];
