import type { FeedPost, StoryUser, SuggestedUser, FeedChallenge } from './feed-types';

export const mockStories: StoryUser[] = [
  { id: '1', name: 'Seu Story', avatar: '', hasStory: false, seen: false },
  { id: '2', name: 'Ana', avatar: 'https://i.pravatar.cc/62?img=5', hasStory: true, seen: false },
  { id: '3', name: 'Carlos', avatar: 'https://i.pravatar.cc/62?img=12', hasStory: true, seen: true },
  { id: '4', name: 'Julia', avatar: 'https://i.pravatar.cc/62?img=9', hasStory: true, seen: false },
  { id: '5', name: 'Pedro', avatar: 'https://i.pravatar.cc/62?img=11', hasStory: true, seen: true },
  { id: '6', name: 'Ana', avatar: 'https://i.pravatar.cc/62?img=16', hasStory: true, seen: false },
  { id: '7', name: 'Thiago', avatar: 'https://i.pravatar.cc/62?img=12', hasStory: true, seen: true },
  { id: '8', name: 'Camila', avatar: 'https://i.pravatar.cc/62?img=20', hasStory: true, seen: false },
];

export const mockPosts: FeedPost[] = [
  {
    id: 'post-001',
    author: {
      id: 'u1',
      name: 'Ana Beatriz',
      username: 'anabeatriz.fit',
      avatar: 'https://i.pravatar.cc/96?img=5',
      isVerified: true,
      level: 42,
    },
    type: 'workout',
    content: {
      text: 'Dia de posterior hoje! Novo PR no leg press: 280kg x 8 reps. A consistência está pagando. Seis meses de dedicação e os resultados aparecem. #gymfire #legday #posterior',
      images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=750&fit=crop'],
    },
    workout: {
      name: 'Treino de Posterior',
      duration: '1h 12m',
      volume: '8.450kg',
      sets: 24,
      exercises: 6,
      calories: 487,
      avgBpm: 142,
    },
    location: 'Smart Fit Pinheiros',
    engagement: { likes: 234, comments: 45, isLiked: false, isSaved: false },
    xpEarned: 120,
    createdAt: new Date(Date.now() - 32 * 60000).toISOString(),
    commentPreview: { username: 'lucas_fit', text: 'Monstro demais! Bora treinar junto semana que vem' },
  },
  {
    id: 'post-002',
    author: {
      id: 'u2',
      name: 'Carlos Eduardo',
      username: 'carlos.runner',
      avatar: 'https://i.pravatar.cc/96?img=12',
      isVerified: false,
      level: 28,
    },
    type: 'run',
    content: {
      text: 'Corrida matinal no Ibirapuera. O nascer do sol tava demais hoje. Quem mais acorda cedo pra treinar? #running #ibirapuera #morningrun',
      images: ['https://images.unsplash.com/photo-1461896836934-bd45ba448c52?w=600&h=750&fit=crop'],
    },
    workout: {
      name: 'Corrida Matinal',
      duration: '52min',
      distance: '10.2km',
      pace: "5'12\"/km",
      calories: 612,
      avgBpm: 156,
    },
    location: 'Parque Ibirapuera',
    engagement: { likes: 187, comments: 32, isLiked: true, isSaved: false },
    xpEarned: 95,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    commentPreview: { username: 'marina_costa', text: 'Ibira de manhã é outro nível' },
  },
  {
    id: 'post-003',
    author: {
      id: 'u3',
      name: 'Marina Costa',
      username: 'marina.costa',
      avatar: 'https://i.pravatar.cc/96?img=9',
      isVerified: true,
      level: 56,
    },
    type: 'challenge',
    content: {
      text: 'Completei o desafio 30 Dias de Fogo! 30 treinos em 30 dias sem faltar um sequer. No começo achei que seria impossível, mas cada dia foi ficando mais fácil. A disciplina vence a motivação. #desafio #30dias #gymfire',
    },
    engagement: { likes: 412, comments: 67, isLiked: false, isSaved: true },
    xpEarned: 500,
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    commentPreview: { username: 'pedro_santos', text: 'Inspiradora demais! Vou começar o meu agora' },
  },
  {
    id: 'post-004',
    author: {
      id: 'u4',
      name: 'Pedro Santos',
      username: 'pedro.iron',
      avatar: 'https://i.pravatar.cc/96?img=11',
      isVerified: false,
      level: 35,
    },
    type: 'personal_record',
    content: {
      text: 'NOVO PR! Supino reto: 120kg x 3 reps. Há 6 meses mal levantava 80kg. A paciência e a técnica fazem toda a diferença. Obrigado @coach_rodrigo pela evolução!',
      images: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=750&fit=crop'],
    },
    personalRecord: {
      exercise: 'Supino Reto',
      newValue: '120kg x 3',
      previousValue: '110kg x 3',
      improvement: '+10kg',
    },
    location: 'Academia Corpo & Ação',
    engagement: { likes: 356, comments: 52, isLiked: false, isSaved: false },
    xpEarned: 150,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    commentPreview: { username: 'anabeatriz.fit', text: 'Que evolução! Parabéns Pedro' },
  },
  {
    id: 'post-005',
    author: {
      id: 'u5',
      name: 'Julia Mendes',
      username: 'ju.mendes',
      avatar: 'https://i.pravatar.cc/96?img=16',
      isVerified: false,
      level: 12,
    },
    type: 'text',
    content: {
      text: '7 dias seguidos treinando! Primeira vez que consigo uma streak dessas. Parece pouco mas pra quem vivia no sedentarismo, é uma vitória enorme. Obrigada a essa comunidade por me motivar todos os dias!',
    },
    engagement: { likes: 89, comments: 18, isLiked: false, isSaved: false },
    xpEarned: 150,
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    commentPreview: { username: 'carlos.runner', text: 'Cada dia conta! Segue firme' },
  },
  {
    id: 'post-006',
    author: {
      id: 'u6',
      name: 'Rafael Lima',
      username: 'rafa.lima',
      avatar: 'https://i.pravatar.cc/96?img=8',
      isVerified: true,
      level: 64,
    },
    type: 'workout',
    content: {
      text: 'CrossFit WOD do dia: Fran em 4:23. Primeiro sub-5 da vida. O coach @rodrigo não me deixou desistir nos thrusters. #crossfit #fran #wod',
      images: ['https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=750&fit=crop'],
    },
    workout: {
      name: 'CrossFit - Fran',
      duration: '4m 23s',
      sets: 6,
      exercises: 2,
      calories: 187,
      avgBpm: 178,
    },
    location: 'CrossFit Box SP',
    engagement: { likes: 289, comments: 41, isLiked: true, isSaved: false },
    xpEarned: 200,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    commentPreview: { username: 'marina.costa', text: 'Sub-5 no Fran é elite! Parabéns Rafa' },
  },
  {
    id: 'post-007',
    author: {
      id: 'u7',
      name: 'Fernanda Silva',
      username: 'fe.silva',
      avatar: 'https://i.pravatar.cc/96?img=25',
      isVerified: false,
      level: 20,
    },
    type: 'run',
    content: {
      text: 'Minha primeira meia maratona! 21km em 2h04. Chorei nos últimos 3km mas terminei. Esse app e essa comunidade me deram forças pra não desistir.',
      images: ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&h=750&fit=crop'],
    },
    workout: {
      name: 'Meia Maratona',
      duration: '2h 04m',
      distance: '21.1km',
      pace: "5'52\"/km",
      calories: 1420,
      avgBpm: 162,
    },
    location: 'Maratona de São Paulo',
    engagement: { likes: 523, comments: 112, isLiked: false, isSaved: true },
    xpEarned: 300,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    commentPreview: { username: 'ju.mendes', text: 'CHOREI LENDO ISSO! Parabéns Fe!!!' },
  },
  {
    id: 'post-008',
    author: {
      id: 'u8',
      name: 'Thiago Rocha',
      username: 'thiago.strong',
      avatar: 'https://i.pravatar.cc/96?img=14',
      isVerified: false,
      level: 31,
    },
    type: 'photo',
    content: {
      text: '3 meses de evolução. Mesmo treino, mesmo espelho, outra pessoa. A transformação não é só física.',
      images: [
        'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=750&fit=crop',
        'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&h=750&fit=crop',
      ],
    },
    engagement: { likes: 445, comments: 78, isLiked: false, isSaved: false },
    xpEarned: 80,
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    commentPreview: { username: 'rafa.lima', text: 'Que shape mano! Dedicação pura' },
  },
];

export const mockSuggestions: SuggestedUser[] = [
  { id: 's1', name: 'Rodrigo Coach', username: 'coach_rodrigo', avatar: 'https://i.pravatar.cc/48?img=33', mutualFollowers: 5 },
  { id: 's2', name: 'Bianca Torres', username: 'bianca.fit', avatar: 'https://i.pravatar.cc/48?img=23', mutualFollowers: 3 },
  { id: 's3', name: 'Lucas Ferreira', username: 'lucas_fit', avatar: 'https://i.pravatar.cc/48?img=18', mutualFollowers: 8 },
  { id: 's4', name: 'Patrícia Souza', username: 'pat.souza', avatar: 'https://i.pravatar.cc/48?img=44', mutualFollowers: 2 },
];

export const mockChallenges: FeedChallenge[] = [
  { id: 'c1', name: '30 Dias de Fogo', progress: 67, participants: 2800 },
  { id: 'c2', name: '100km Challenge', progress: 42, participants: 1300 },
  { id: 'c3', name: 'PR Destroyer', progress: 85, participants: 950 },
];
