import type { ProfileData } from './profile-types';
import { getTier } from './profile-types';

export const mockProfile: ProfileData = {
  id: 'self',
  username: 'usuario',
  displayName: 'Usuário GymFire',
  bio: 'Treinando consistência todos os dias.',
  avatar: '',
  isVerified: false,
  level: 21,
  xp: 7450,
  xpToNext: 2550,
  tier: getTier(21),
  stats: {
    workouts: 89,
    workoutsThisWeek: 4,
    streak: 18,
    streakRecord: 32,
    totalVolume: 142000,
    prs: 12,
  },
  social: { followers: 234, following: 156, posts: 47 },
  weeklyActivity: [true, true, false, true, true, false, false],
  activityRings: {
    calories: { current: 1850, goal: 2500 },
    workouts: { current: 4, goal: 4 },
    activeTime: { current: 280, goal: 360 },
    hydration: { current: 2100, goal: 3000 },
  },
  history: [
    { id: 'h1', name: 'Treino de Posterior', date: '2026-03-31', duration: '1h 12m', volume: '8.450kg', sets: 24, calories: 487, exercises: ['Leg Press', 'Stiff', 'Cadeira Flexora', 'Mesa Flexora'] },
    { id: 'h2', name: 'Treino de Peito', date: '2026-03-30', duration: '58min', volume: '6.200kg', sets: 20, calories: 412, exercises: ['Supino Reto', 'Crucifixo', 'Crossover', 'Flexão'] },
    { id: 'h3', name: 'Corrida Matinal', date: '2026-03-29', duration: '45min', volume: '-', sets: 0, calories: 520, exercises: ['Corrida 8km'] },
    { id: 'h4', name: 'Treino de Costas', date: '2026-03-28', duration: '1h 05m', volume: '7.800kg', sets: 22, calories: 456, exercises: ['Barra Fixa', 'Remada', 'Puxada', 'Serrote'] },
    { id: 'h5', name: 'Treino de Ombros', date: '2026-03-27', duration: '52min', volume: '4.300kg', sets: 18, calories: 345, exercises: ['Desenvolvimento', 'Elevação Lateral', 'Face Pull'] },
    { id: 'h6', name: 'CrossFit WOD', date: '2026-03-26', duration: '35min', volume: '3.200kg', sets: 12, calories: 380, exercises: ['Thrusters', 'Pull-ups', 'Box Jumps'] },
    { id: 'h7', name: 'Treino de Braços', date: '2026-03-25', duration: '48min', volume: '3.600kg', sets: 20, calories: 290, exercises: ['Rosca Direta', 'Tríceps Corda', 'Martelo', 'Francês'] },
    { id: 'h8', name: 'Treino de Pernas', date: '2026-03-24', duration: '1h 20m', volume: '12.400kg', sets: 28, calories: 620, exercises: ['Agachamento', 'Leg Press', 'Extensora', 'Panturrilha'] },
  ],
  records: [
    { id: 'pr1', exercise: 'Supino Reto', currentValue: '120kg x 3', previousValue: '110kg x 3', improvement: '+10kg', isNew: false, date: '2026-03-28' },
    { id: 'pr2', exercise: 'Agachamento', currentValue: '160kg x 5', previousValue: '150kg x 5', improvement: '+10kg', isNew: true, date: '2026-03-31' },
    { id: 'pr3', exercise: 'Leg Press', currentValue: '280kg x 8', previousValue: '260kg x 8', improvement: '+20kg', isNew: true, date: '2026-03-31' },
    { id: 'pr4', exercise: 'Barra Fixa', currentValue: '15 reps', previousValue: '12 reps', improvement: '+3 reps', isNew: false, date: '2026-03-20' },
    { id: 'pr5', exercise: 'Desenvolvimento', currentValue: '60kg x 6', previousValue: '55kg x 6', improvement: '+5kg', isNew: false, date: '2026-03-15' },
    { id: 'pr6', exercise: 'Remada Curvada', currentValue: '90kg x 8', previousValue: '85kg x 8', improvement: '+5kg', isNew: false, date: '2026-03-10' },
    { id: 'pr7', exercise: 'Rosca Direta', currentValue: '45kg x 8', previousValue: '40kg x 8', improvement: '+5kg', isNew: false, date: '2026-03-05' },
    { id: 'pr8', exercise: 'Stiff', currentValue: '100kg x 10', previousValue: '90kg x 10', improvement: '+10kg', isNew: false, date: '2026-02-28' },
  ],
  achievements: [
    { id: 'a1', title: 'Primeiro Treino', description: 'Complete seu primeiro treino', unlocked: true, icon: 'flame', rarity: 'common' },
    { id: 'a2', title: 'Consistente', description: '7 dias seguidos de treino', unlocked: true, icon: 'zap', rarity: 'common' },
    { id: 'a3', title: 'Dedicado', description: '30 treinos completados', unlocked: true, icon: 'star', rarity: 'common' },
    { id: 'a4', title: 'Máquina', description: '50 treinos completados', unlocked: true, icon: 'trophy', rarity: 'rare' },
    { id: 'a5', title: 'Veterano', description: '100 treinos completados', unlocked: false, progress: 89, icon: 'medal', rarity: 'rare' },
    { id: 'a6', title: 'PR Hunter', description: 'Bata 5 recordes pessoais', unlocked: true, icon: 'target', rarity: 'rare' },
    { id: 'a7', title: 'PR Destroyer', description: 'Bata 20 recordes pessoais', unlocked: false, progress: 60, icon: 'crown', rarity: 'epic' },
    { id: 'a8', title: 'Fogo Eterno', description: '30 dias de streak', unlocked: true, icon: 'flame', rarity: 'epic' },
    { id: 'a9', title: 'Toneladas', description: 'Levante 100 toneladas no total', unlocked: true, icon: 'mountain', rarity: 'epic' },
    { id: 'a10', title: 'Ironman', description: 'Levante 500 toneladas no total', unlocked: false, progress: 28, icon: 'mountain', rarity: 'legendary' },
    { id: 'a11', title: 'Madrugador', description: 'Treine antes das 6h', unlocked: true, icon: 'star', rarity: 'common' },
    { id: 'a12', title: 'Social Fitness', description: '100 seguidores', unlocked: true, icon: 'trophy', rarity: 'rare' },
    { id: 'a13', title: 'Influencer', description: '1000 seguidores', unlocked: false, progress: 23, icon: 'crown', rarity: 'legendary' },
    { id: 'a14', title: 'Desafiante', description: 'Complete 3 desafios', unlocked: true, icon: 'target', rarity: 'rare' },
    { id: 'a15', title: 'All Rounder', description: 'Treine 5 grupos musculares diferentes', unlocked: true, icon: 'zap', rarity: 'common' },
    { id: 'a16', title: 'Mestre Supremo', description: 'Alcance o nível 50', unlocked: false, progress: 42, icon: 'crown', rarity: 'legendary' },
  ],
  monthlyVolume: [
    { month: 'Out', value: 42000 },
    { month: 'Nov', value: 55000 },
    { month: 'Dez', value: 48000 },
    { month: 'Jan', value: 62000 },
    { month: 'Fev', value: 71000 },
    { month: 'Mar', value: 78000 },
  ],
  memberSince: '2025-09-15',
};
