import {
  MuscleGroup,
  Equipment,
  ExerciseCategory,
  Difficulty,
} from '@prisma/client';

export const defaultExercises = [
  {
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    description: 'A compound chest exercise using a barbell on a flat bench.',
    instructions: ['Lie on a flat bench', 'Grip the bar slightly wider than shoulder width', 'Lower the bar to your chest', 'Press the bar back up to full extension'],
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    description: 'An upper chest exercise performed on an incline bench with dumbbells.',
    instructions: ['Set bench to 30-45 degree incline', 'Press dumbbells up from shoulder level', 'Lower with control to chest level', 'Keep feet flat on the floor'],
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    description: 'A fundamental lower body compound exercise.',
    instructions: ['Place bar on upper back', 'Feet shoulder-width apart', 'Descend until thighs are parallel to the floor', 'Drive through heels to stand'],
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Conventional Deadlift',
    slug: 'conventional-deadlift',
    description: 'A full-body compound pulling exercise from the floor.',
    instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Keep back flat and chest up', 'Drive through the floor to stand'],
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.ADVANCED,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    description: 'A standing barbell press targeting the shoulders.',
    instructions: ['Grip bar at shoulder width', 'Press bar overhead to full lockout', 'Lower with control back to shoulders', 'Keep core tight throughout'],
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Pull-Up',
    slug: 'pull-up',
    description: 'A bodyweight vertical pulling exercise.',
    instructions: ['Grip bar with palms facing away', 'Hang with arms fully extended', 'Pull yourself up until chin clears the bar', 'Lower with control'],
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.PULL_UP_BAR,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Barbell Row',
    slug: 'barbell-row',
    description: 'A compound rowing movement for back thickness.',
    instructions: ['Hinge at hips with slight knee bend', 'Grip bar shoulder-width', 'Row bar to lower chest/upper abdomen', 'Squeeze shoulder blades at the top'],
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    description: 'An isolation exercise for the lateral deltoids.',
    instructions: ['Stand with dumbbells at sides', 'Raise arms out to sides until parallel with floor', 'Slight bend in elbows', 'Lower with control'],
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Barbell Curl',
    slug: 'barbell-curl',
    description: 'A classic biceps isolation exercise with a barbell.',
    instructions: ['Stand with barbell at arm length', 'Curl the bar up keeping elbows stationary', 'Squeeze at the top', 'Lower with control'],
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    description: 'A cable isolation exercise for the triceps.',
    instructions: ['Grip cable attachment at chest height', 'Push down until arms are fully extended', 'Keep elbows pinned to sides', 'Return with control'],
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    description: 'A machine-based compound leg exercise.',
    instructions: ['Sit in leg press machine', 'Place feet shoulder-width on platform', 'Lower platform by bending knees to 90 degrees', 'Press back to starting position'],
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    description: 'A hip-hinge exercise targeting the posterior chain.',
    instructions: ['Hold barbell at hip level', 'Push hips back while lowering bar along legs', 'Keep slight knee bend and back flat', 'Return to standing by driving hips forward'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description: 'A cable machine exercise targeting the latissimus dorsi.',
    instructions: ['Grip bar wider than shoulder width', 'Pull bar down to upper chest', 'Squeeze lats at the bottom', 'Return with control overhead'],
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Chest Fly',
    slug: 'dumbbell-chest-fly',
    description: 'An isolation exercise for chest stretch and contraction.',
    instructions: ['Lie on flat bench with dumbbells above chest', 'Lower arms out to sides with slight elbow bend', 'Feel the stretch in the chest', 'Bring dumbbells back together at the top'],
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Cable Face Pull',
    slug: 'cable-face-pull',
    description: 'A cable exercise for rear deltoids and upper back health.',
    instructions: ['Set cable at upper chest height', 'Pull rope towards face with elbows high', 'Externally rotate at the end', 'Squeeze rear delts and return'],
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dip',
    slug: 'dip',
    description: 'A compound bodyweight exercise for chest and triceps.',
    instructions: ['Grip parallel bars and support your body', 'Lower yourself until upper arms are parallel to floor', 'Lean forward for chest emphasis or stay upright for triceps', 'Press back up to full extension'],
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DIP_BAR,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Curl',
    slug: 'leg-curl',
    description: 'A machine isolation exercise for the hamstrings.',
    instructions: ['Lie face down on leg curl machine', 'Curl weight up by bending knees', 'Squeeze hamstrings at the top', 'Lower with control'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Extension',
    slug: 'leg-extension',
    description: 'A machine isolation exercise for the quadriceps.',
    instructions: ['Sit in leg extension machine', 'Extend legs until straight', 'Squeeze quads at the top', 'Lower with control'],
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Plank',
    slug: 'plank',
    description: 'An isometric core stabilization exercise.',
    instructions: ['Get into push-up position on forearms', 'Keep body in a straight line', 'Engage core and glutes', 'Hold for the prescribed duration'],
    muscleGroup: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    category: ExerciseCategory.ENDURANCE,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Calf Raise',
    slug: 'calf-raise',
    description: 'An isolation exercise for the calf muscles.',
    instructions: ['Stand on edge of a step or platform', 'Rise up onto toes as high as possible', 'Pause at the top and squeeze', 'Lower heels below platform level'],
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    description: 'A glute-focused hip extension exercise.',
    instructions: ['Sit with upper back against a bench', 'Place barbell across hips', 'Drive hips up until body forms a straight line', 'Squeeze glutes at the top and lower'],
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    category: ExerciseCategory.STRENGTH,
    difficulty: Difficulty.INTERMEDIATE,
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    description: 'A biceps and brachialis exercise with neutral grip.',
    instructions: ['Hold dumbbells at sides with palms facing each other', 'Curl weights up keeping neutral grip', 'Squeeze at the top', 'Lower with control'],
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    category: ExerciseCategory.HYPERTROPHY,
    difficulty: Difficulty.BEGINNER,
    isPublic: true,
    isFromLibrary: true,
  },
];
