import * as dotenv from 'dotenv';
dotenv.config();

import { PrismaClient, MuscleGroup, Equipment, ExerciseCategory, Difficulty } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const exerciseLibrary = [
  // ── CHEST ────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'The bench press is a compound exercise that targets the chest, shoulders, and triceps.',
    instructions: ['Lie on a flat bench with feet flat on the floor', 'Grip the bar slightly wider than shoulder width', 'Lower the bar to mid-chest with control', 'Press the bar back up to full lockout'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An upper chest exercise performed on an incline bench with dumbbells.',
    instructions: ['Set bench to 30-45 degree incline', 'Press dumbbells up from shoulder level', 'Lower with control to chest level', 'Keep feet flat on the floor'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Chest Fly',
    slug: 'dumbbell-chest-fly',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An isolation exercise for chest stretch and contraction.',
    instructions: ['Lie on flat bench with dumbbells above chest', 'Lower arms out to sides with slight elbow bend', 'Feel the stretch in the chest', 'Bring dumbbells back together at the top'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Cable Crossover',
    slug: 'cable-crossover',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A cable exercise providing constant tension on the chest throughout the range of motion.',
    instructions: ['Set cables at high position', 'Step forward with one foot', 'Bring handles together in front of chest in arc motion', 'Squeeze chest at the bottom and return slowly'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dip',
    slug: 'dip',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DIP_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A compound bodyweight exercise for chest and triceps.',
    instructions: ['Grip parallel bars and support your body', 'Lower yourself until upper arms are parallel to floor', 'Lean forward for chest emphasis', 'Press back up to full extension'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Machine Chest Press',
    slug: 'machine-chest-press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A machine-based pressing movement for building chest mass safely.',
    instructions: ['Adjust seat height so handles are at chest level', 'Grip handles firmly', 'Press forward until arms are extended', 'Return with control to starting position'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── BACK ─────────────────────────────────────────────────────
  {
    name: 'Conventional Deadlift',
    slug: 'conventional-deadlift',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.STRENGTH,
    description: 'A full-body compound pulling exercise from the floor.',
    instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Keep back flat and chest up', 'Drive through the floor to stand'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Pull-Up',
    slug: 'pull-up',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.PULL_UP_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A bodyweight vertical pulling exercise.',
    instructions: ['Grip bar with palms facing away', 'Hang with arms fully extended', 'Pull yourself up until chin clears the bar', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Barbell Row',
    slug: 'barbell-row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A compound rowing movement for back thickness.',
    instructions: ['Hinge at hips with slight knee bend', 'Grip bar shoulder-width', 'Row bar to lower chest or upper abdomen', 'Squeeze shoulder blades at the top'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A cable machine exercise targeting the latissimus dorsi.',
    instructions: ['Grip bar wider than shoulder width', 'Pull bar down to upper chest', 'Squeeze lats at the bottom', 'Return with control overhead'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A seated rowing exercise using a cable machine for mid-back development.',
    instructions: ['Sit with feet on the platform and knees slightly bent', 'Grip the handle with both hands', 'Pull the handle towards your torso', 'Squeeze shoulder blades together and return slowly'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'T-Bar Row',
    slug: 't-bar-row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A barbell rowing variation that targets the mid-back with a neutral grip.',
    instructions: ['Straddle the barbell or use a T-bar station', 'Grip the handle with both hands', 'Row the weight towards your chest', 'Lower with control keeping back flat'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── SHOULDERS ────────────────────────────────────────────────
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A standing barbell press targeting the shoulders.',
    instructions: ['Grip bar at shoulder width', 'Press bar overhead to full lockout', 'Lower with control back to shoulders', 'Keep core tight throughout'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An isolation exercise for the lateral deltoids.',
    instructions: ['Stand with dumbbells at sides', 'Raise arms out to sides until parallel with floor', 'Slight bend in elbows', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Cable Face Pull',
    slug: 'cable-face-pull',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A cable exercise for rear deltoids and upper back health.',
    instructions: ['Set cable at upper chest height', 'Pull rope towards face with elbows high', 'Externally rotate at the end', 'Squeeze rear delts and return'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Arnold Press',
    slug: 'arnold-press',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A dumbbell press variation with rotation that targets all three deltoid heads.',
    instructions: ['Start with dumbbells at shoulder height, palms facing you', 'Press overhead while rotating palms to face forward', 'Reverse the motion on the way down', 'Maintain controlled tempo throughout'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Rear Delt Fly',
    slug: 'dumbbell-rear-delt-fly',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An isolation exercise targeting the rear deltoids.',
    instructions: ['Bend at hips with dumbbells hanging below', 'Raise arms out to sides squeezing rear delts', 'Keep slight bend in elbows', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── BICEPS ───────────────────────────────────────────────────
  {
    name: 'Barbell Curl',
    slug: 'barbell-curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A classic biceps isolation exercise with a barbell.',
    instructions: ['Stand with barbell at arm length', 'Curl the bar up keeping elbows stationary', 'Squeeze at the top', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A biceps and brachialis exercise with neutral grip.',
    instructions: ['Hold dumbbells at sides with palms facing each other', 'Curl weights up keeping neutral grip', 'Squeeze at the top', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Incline Dumbbell Curl',
    slug: 'incline-dumbbell-curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A dumbbell curl performed on an incline bench for extra stretch on the biceps.',
    instructions: ['Set bench to 45 degree incline and sit back', 'Let arms hang straight down with dumbbells', 'Curl weights up without moving upper arms', 'Lower slowly to full extension'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'EZ Bar Preacher Curl',
    slug: 'ez-bar-preacher-curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.EZ_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A preacher bench curl using an EZ bar for focused biceps isolation.',
    instructions: ['Sit at preacher bench with armpits at top of pad', 'Grip EZ bar at inner angled grip', 'Curl bar up squeezing biceps', 'Lower with control to near full extension'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── TRICEPS ──────────────────────────────────────────────────
  {
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A cable isolation exercise for the triceps.',
    instructions: ['Grip cable attachment at chest height', 'Push down until arms are fully extended', 'Keep elbows pinned to sides', 'Return with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Skull Crusher',
    slug: 'skull-crusher',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.EZ_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A lying triceps extension using an EZ bar for tricep mass.',
    instructions: ['Lie on bench holding EZ bar above chest', 'Bend elbows to lower bar towards forehead', 'Keep upper arms stationary', 'Extend arms back to starting position'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Overhead Tricep Extension',
    slug: 'overhead-tricep-extension',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A single dumbbell overhead extension targeting the long head of the triceps.',
    instructions: ['Hold dumbbell overhead with both hands', 'Lower behind head by bending elbows', 'Keep upper arms close to ears', 'Extend arms back overhead'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Close Grip Bench Press',
    slug: 'close-grip-bench-press',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A bench press variation with narrow grip emphasizing the triceps.',
    instructions: ['Lie on bench and grip bar shoulder-width apart', 'Lower bar to lower chest keeping elbows tucked', 'Press up focusing on tricep contraction', 'Lock out at the top'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── FOREARMS ─────────────────────────────────────────────────
  {
    name: 'Wrist Curl',
    slug: 'wrist-curl',
    muscleGroup: MuscleGroup.FOREARMS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An isolation exercise for the forearm flexors.',
    instructions: ['Sit with forearms on thighs, wrists over knees', 'Hold barbell with underhand grip', 'Curl wrists upward', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── QUADS ────────────────────────────────────────────────────
  {
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A fundamental lower body compound exercise.',
    instructions: ['Place bar on upper back', 'Feet shoulder-width apart', 'Descend until thighs are parallel to the floor', 'Drive through heels to stand'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Front Squat',
    slug: 'front-squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.STRENGTH,
    description: 'A squat variation with the bar on the front of the shoulders for increased quad emphasis.',
    instructions: ['Rest bar on front deltoids with clean or cross grip', 'Keep elbows high and chest up', 'Squat down keeping torso upright', 'Drive up through the whole foot'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.STRENGTH,
    description: 'A machine-based compound leg exercise.',
    instructions: ['Sit in leg press machine', 'Place feet shoulder-width on platform', 'Lower platform by bending knees to 90 degrees', 'Press back to starting position'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Extension',
    slug: 'leg-extension',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A machine isolation exercise for the quadriceps.',
    instructions: ['Sit in leg extension machine', 'Extend legs until straight', 'Squeeze quads at the top', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Bulgarian Split Squat',
    slug: 'bulgarian-split-squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A unilateral squat with the rear foot elevated for increased range of motion.',
    instructions: ['Place rear foot on a bench behind you', 'Hold dumbbells at sides', 'Lower until front thigh is parallel to floor', 'Push through front foot to stand'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── HAMSTRINGS ───────────────────────────────────────────────
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A hip-hinge exercise targeting the posterior chain.',
    instructions: ['Hold barbell at hip level', 'Push hips back while lowering bar along legs', 'Keep slight knee bend and back flat', 'Return to standing by driving hips forward'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Leg Curl',
    slug: 'leg-curl',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A machine isolation exercise for the hamstrings.',
    instructions: ['Lie face down on leg curl machine', 'Curl weight up by bending knees', 'Squeeze hamstrings at the top', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Nordic Hamstring Curl',
    slug: 'nordic-hamstring-curl',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.STRENGTH,
    description: 'An advanced bodyweight exercise for hamstring strength and injury prevention.',
    instructions: ['Kneel with ankles secured under a pad or by a partner', 'Slowly lower your body forward keeping hips extended', 'Lower as far as you can control', 'Push off the ground to return or use eccentric only'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── GLUTES ───────────────────────────────────────────────────
  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A glute-focused hip extension exercise.',
    instructions: ['Sit with upper back against a bench', 'Place barbell across hips', 'Drive hips up until body forms a straight line', 'Squeeze glutes at the top and lower'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Cable Kickback',
    slug: 'cable-kickback',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A cable exercise isolating the glutes through hip extension.',
    instructions: ['Attach ankle strap to low cable', 'Stand facing the machine', 'Kick leg straight back squeezing glute', 'Return with control to starting position'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── CALVES ───────────────────────────────────────────────────
  {
    name: 'Standing Calf Raise',
    slug: 'standing-calf-raise',
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A machine exercise for the calf muscles performed standing.',
    instructions: ['Stand on calf raise machine with shoulders under pads', 'Rise up onto toes as high as possible', 'Pause at the top and squeeze', 'Lower heels below platform level for full stretch'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Seated Calf Raise',
    slug: 'seated-calf-raise',
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A seated calf exercise targeting the soleus muscle.',
    instructions: ['Sit in seated calf raise machine', 'Place balls of feet on the platform', 'Raise heels as high as possible', 'Lower slowly for a full stretch'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── CORE / ABS ───────────────────────────────────────────────
  {
    name: 'Plank',
    slug: 'plank',
    muscleGroup: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.ENDURANCE,
    description: 'An isometric core stabilization exercise.',
    instructions: ['Get into push-up position on forearms', 'Keep body in a straight line', 'Engage core and glutes', 'Hold for the prescribed duration'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.CORE],
    equipment: Equipment.PULL_UP_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A hanging exercise that targets the lower abs.',
    instructions: ['Hang from a pull-up bar with arms extended', 'Raise legs until parallel to the floor or higher', 'Avoid swinging or using momentum', 'Lower legs with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Cable Crunch',
    slug: 'cable-crunch',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'A kneeling crunch using cable resistance for ab development.',
    instructions: ['Kneel below a high cable with rope attachment', 'Hold rope behind head', 'Crunch down bringing elbows towards knees', 'Return to starting position with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Ab Wheel Rollout',
    slug: 'ab-wheel-rollout',
    muscleGroup: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ABS],
    equipment: Equipment.OTHER,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.STRENGTH,
    description: 'An advanced core exercise using an ab wheel for anti-extension strength.',
    instructions: ['Kneel on the floor gripping the ab wheel', 'Roll forward extending your body', 'Go as far as you can while maintaining a flat back', 'Pull yourself back to the starting position'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── FULL BODY ────────────────────────────────────────────────
  {
    name: 'Clean and Press',
    slug: 'clean-and-press',
    muscleGroup: MuscleGroup.FULL_BODY,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.BACK, MuscleGroup.QUADS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.POWER,
    description: 'An Olympic-style compound movement combining a clean with an overhead press.',
    instructions: ['Start with barbell on the floor', 'Clean the bar to shoulder height in one explosive movement', 'Press the bar overhead to lockout', 'Lower bar back to shoulders then to floor'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Kettlebell Swing',
    slug: 'kettlebell-swing',
    muscleGroup: MuscleGroup.FULL_BODY,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.KETTLEBELL,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.POWER,
    description: 'A ballistic hip-hinge exercise using a kettlebell for power and conditioning.',
    instructions: ['Stand with feet shoulder-width apart, kettlebell in front', 'Hinge at hips and swing kettlebell between legs', 'Drive hips forward to swing kettlebell to chest height', 'Let it swing back between legs and repeat'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Burpee',
    slug: 'burpee',
    muscleGroup: MuscleGroup.FULL_BODY,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.QUADS, MuscleGroup.CORE],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.CARDIO,
    description: 'A full-body bodyweight exercise combining a squat, push-up, and jump.',
    instructions: ['Start standing then drop into a squat position', 'Kick feet back into push-up position', 'Perform a push-up', 'Jump feet forward and explode upward into a jump'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Turkish Get-Up',
    slug: 'turkish-get-up',
    muscleGroup: MuscleGroup.FULL_BODY,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.CORE, MuscleGroup.GLUTES],
    equipment: Equipment.KETTLEBELL,
    difficulty: Difficulty.ADVANCED,
    category: ExerciseCategory.STRENGTH,
    description: 'A complex multi-step exercise transitioning from lying to standing while holding a weight overhead.',
    instructions: ['Lie on your back holding kettlebell above one shoulder', 'Roll to elbow then to hand', 'Sweep leg through to kneeling position', 'Stand up keeping weight overhead, then reverse'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── CARDIO ───────────────────────────────────────────────────
  {
    name: 'Treadmill Run',
    slug: 'treadmill-run',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CALVES],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.CARDIO,
    description: 'Running on a treadmill for cardiovascular conditioning.',
    instructions: ['Set desired speed and incline', 'Run with natural stride', 'Maintain steady breathing', 'Cool down by reducing speed gradually'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Rowing Machine',
    slug: 'rowing-machine',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.QUADS, MuscleGroup.CORE],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.CARDIO,
    description: 'A full-body cardio exercise using a rowing ergometer.',
    instructions: ['Sit on the rower and strap feet in', 'Grab handle with overhand grip', 'Drive with legs then pull with arms', 'Return by extending arms then bending knees'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Jump Rope',
    slug: 'jump-rope',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.CALVES, MuscleGroup.SHOULDERS],
    equipment: Equipment.OTHER,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.CARDIO,
    description: 'A classic cardio exercise using a skipping rope.',
    instructions: ['Hold rope handles at hip height', 'Swing rope overhead and jump with both feet', 'Land softly on balls of feet', 'Keep jumps small and consistent'],
    isPublic: true,
    isFromLibrary: true,
  },

  // ── ADDITIONAL VARIETY ───────────────────────────────────────
  {
    name: 'Smith Machine Squat',
    slug: 'smith-machine-squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.SMITH_MACHINE,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.STRENGTH,
    description: 'A squat performed on a Smith machine for added stability.',
    instructions: ['Position bar on upper back under Smith machine', 'Feet slightly forward of bar', 'Squat down to parallel', 'Press up to standing'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Trap Bar Deadlift',
    slug: 'trap-bar-deadlift',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.TRAP_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A deadlift variation using a trap bar that is easier on the lower back.',
    instructions: ['Step inside the trap bar', 'Grip the handles at your sides', 'Drive through feet to stand up', 'Lower with control back to the floor'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Resistance Band Pull Apart',
    slug: 'resistance-band-pull-apart',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.RESISTANCE_BAND,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.REHABILITATION,
    description: 'A band exercise for shoulder health and rear delt activation.',
    instructions: ['Hold band in front with arms extended', 'Pull band apart by squeezing shoulder blades', 'Hold the stretched position briefly', 'Return to start with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Goblet Squat',
    slug: 'goblet-squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: Equipment.KETTLEBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.STRENGTH,
    description: 'A beginner-friendly squat holding a kettlebell at chest level.',
    instructions: ['Hold kettlebell at chest with both hands', 'Stand with feet shoulder-width apart', 'Squat down keeping chest up and elbows inside knees', 'Stand back up driving through heels'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Push-Up',
    slug: 'push-up',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.STRENGTH,
    description: 'A foundational bodyweight pushing exercise.',
    instructions: ['Start in a high plank with hands under shoulders', 'Lower chest to the floor keeping body straight', 'Push back up to full arm extension', 'Maintain core engagement throughout'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Chin-Up',
    slug: 'chin-up',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: Equipment.PULL_UP_BAR,
    difficulty: Difficulty.INTERMEDIATE,
    category: ExerciseCategory.STRENGTH,
    description: 'A pulling exercise with supinated grip emphasizing biceps and lats.',
    instructions: ['Grip bar with palms facing you, shoulder-width apart', 'Hang with arms extended', 'Pull up until chin clears the bar', 'Lower with control to full extension'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Dumbbell Shrug',
    slug: 'dumbbell-shrug',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.HYPERTROPHY,
    description: 'An isolation exercise targeting the upper trapezius.',
    instructions: ['Hold dumbbells at your sides', 'Shrug shoulders straight up towards ears', 'Hold at the top and squeeze traps', 'Lower with control'],
    isPublic: true,
    isFromLibrary: true,
  },
  {
    name: 'Lunges',
    slug: 'lunges',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    category: ExerciseCategory.STRENGTH,
    description: 'A unilateral lower body exercise that improves balance and leg strength.',
    instructions: ['Stand tall with feet hip-width apart', 'Step forward with one leg', 'Lower until both knees are at 90 degrees', 'Push off front foot to return to standing'],
    isPublic: true,
    isFromLibrary: true,
  },
];

async function main() {
  console.log('Seeding exercise library...');

  let created = 0;
  let skipped = 0;

  for (const exercise of exerciseLibrary) {
    const existing = await prisma.exercise.findUnique({
      where: { slug: exercise.slug },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.exercise.create({ data: exercise });
    created++;
  }

  console.log(`Exercise library seeded: ${created} created, ${skipped} skipped (already exist).`);
  console.log(`Total exercises in library: ${exerciseLibrary.length}`);
}

main()
  .catch((e) => {
    console.error('Error seeding exercises:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
